name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stage
          - prod

      component:
        description: "Choose Terraform component"
        required: true
        default: "vpc"
        type: choice
        options:
          - vpc
          - ec2
          - rds

      action:
        description: "Terraform action"
        required: true
        default: "plan"
        type: choice
        options:
          - init
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./run-terraform.sh

      - name: Run Terraform
        run: |
          ./run-terraform.sh ${{ github.event.inputs.action }} components=${{ github.event.inputs.component }}