name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stage
          - prod

      component:
        description: "Choose Terraform component"
        required: true
        default: "vpc"
        type: choice
        options:
          - vpc
          - ec2
          - rds

      action:
        description: "Terraform action"
        required: true
        default: "plan"
        type: choice
        options:
          - init
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: Build Terraform Docker Image
        run: docker compose build --no-cache

      - name: Make script executable
        run: chmod +x ./run-terraform.sh
      - name: Check repo files
        run: |
          pwd
          ls -la
          ls -la terraform/components
          ls -la terraform/components/vpc
          ls -la terraform/components/vpc/backend 

      - name: Run Terraform
        run: |
          ./run-terraform.sh ${{ github.event.inputs.action }} components=${{ github.event.inputs.component }}